# Generated by Django 6.0.6 on 2026-06-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_bidder_bid_border_auction_buy_now_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='border',
            new_name='bidder',
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=20),
        ),
    ]
