# Generated by Django 6.0.6 on 2026-06-28 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_border_bid_bidder_alter_auction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
