# Generated by Django 6.0.6 on 2026-06-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_winner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_refused',
            field=models.BooleanField(default=False),
        ),
    ]
