# Generated by Django 6.0.6 on 2026-06-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auction_is_refused'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='refusal_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
