# Generated by Django 6.0.6 on 2026-07-01 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_duration', models.IntegerField(default=1)),
                ('listing_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('success_fee_percent', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('min_success_fee', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('max_success_fee', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('fee_rules_status', models.CharField(default='Active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_rules', to='auctions.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_address', models.TextField(default='Chưa cập nhật')),
                ('order_status', models.CharField(default='Pending', max_length=50)),
                ('total_platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='auctions.auction')),
                ('fee_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.feerule')),
            ],
        ),
    ]
