# Generated by Django 6.0.6 on 2026-08-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_feerule_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'verbose_name': 'Phiên đấu giá', 'verbose_name_plural': 'Phiên đấu giá'},
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Lượt đặt giá', 'verbose_name_plural': 'Lượt đặt giá'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Bình luận', 'verbose_name_plural': 'Bình luận'},
        ),
        migrations.AlterModelOptions(
            name='feerule',
            options={'verbose_name': 'Luật phí', 'verbose_name_plural': 'Luật phí'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Đánh giá', 'verbose_name_plural': 'Đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'verbose_name': 'Mục theo dõi', 'verbose_name_plural': 'Mục theo dõi'},
        ),
        migrations.AddField(
            model_name='auction',
            name='contact_info',
            field=models.CharField(blank=True, default='Chưa cập nhật', max_length=255),
        ),
    ]
