# Generated by Django 6.0.6 on 2026-08-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_auction_options_alter_bid_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='contact_info',
            field=models.CharField(default='Chưa cập nhật', max_length=255),
        ),
    ]
